version: 2.1
jobs:
  build:
    docker:
      - image: vproxy/ci-rust:202009121101
    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - checkout
      - run: cargo build --target x86_64-pc-windows-gnu --release
