version: 2.1
jobs:
  build:
    docker:
      - image: vproxy/ci-rust:202009120952
    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - checkout
      - run: cross +stable build --target x86_64-pc-windows-gnu --release
