version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: "Install Rust/Cargo/Cross"
          command: |
            sudo apt-get update -y;
            sudo apt-get install -y build-essential binfmt-support qemu-user-static musl-tools curl wget iptables xz-utils btrfs-progs;
            sudo apt-get clean;
            curl -o ./rustup-init https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init && \
            chmod +x /rustup-init;
            /rustup-init -y;
            rm -f /rustup-init;
            source $HOME/.cargo/env;
            cargo install cross;
      - run:
          name: "Build for armv7-unknown-linux-musleabihf"
          command: |
            source $HOME/.cargo/env; 
            cross build --target armv7-unknown-linux-musleabihf --release; 
            mkdir -p docker/bin/armv7-unknown-linux-musleabihf;
            cp -r ./docker/web docker/bin/armv7-unknown-linux-musleabihf/;
            cp target/armv7-unknown-linux-musleabihf/release/v-proxy docker/bin/armv7-unknown-linux-musleabihf/;
            tar -czvf docker/bin/armv7-unknown-linux-musleabihf.tar.gz docker/bin/armv7-unknown-linux-musleabihf/*;
      - persist_to_workspace:
          root: docker/bin
          paths:
            - armv7-unknown-linux-musleabihf.tar.gz
            - armv7-unknown-linux-musleabihf/
  


  deploy:
    docker:
      - image: vproxy/ci-rust:202009130603
    steps:
      - checkout
      - attach_workspace:
          at: docker/bin
      - run: dockerd
      - run: ls docker/bin; ls armv7-unknown-linux-musleabihf/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build




