version: 2.1
jobs:
  x86_64-pc-windows-gnu:
    docker:
      - image: vproxy/ci-rust:202009130603
    steps:
      - checkout
      - run: cargo build --target x86_64-pc-windows-gnu --release; 
      - run:
          name: "Create Artifacts Package"
          command: |
            mkdir -p docker/bin/x86_64-pc-windows-gnu;
            cp -r ./docker/web docker/bin/x86_64-pc-windows-gnu/;
            cp target/x86_64-pc-windows-gnu/release/v-proxy.exe docker/bin/x86_64-pc-windows-gnu/;
            zip -r docker/bin/x86_64-pc-windows-gnu.zip docker/bin/x86_64-pc-windows-gnu/*;
      - persist_to_workspace:
          root: docker/bin
          paths:
            - x86_64-pc-windows-gnu.zip
            - x86_64-pc-windows-gnu/

  x86_64-unknown-linux-gnu:
    docker:
      - image: vproxy/ci-rust:202009130603
    steps:
      - checkout
      - run: cargo build --target x86_64-unknown-linux-gnu --release; 
      - run:
          name: "Create Artifacts Package"
          command: |
            mkdir -p docker/bin/x86_64-unknown-linux-gnu;
            cp -r ./docker/web docker/bin/x86_64-unknown-linux-gnu/;
            cp target/x86_64-unknown-linux-gnu/release/v-proxy docker/bin/x86_64-unknown-linux-gnu/;
            tar -czvf docker/bin/x86_64-unknown-linux-gnu.tar.gz docker/bin/x86_64-unknown-linux-gnu/*;
      - persist_to_workspace:
          root: docker/bin
          paths:
            - x86_64-unknown-linux-gnu.tar.gz
            - x86_64-unknown-linux-gnu/

  armv7-unknown-linux-musleabihf:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: "Install Rust/Cargo/Cross"
          command: |
            apt-get update -y;
            apt-get install -y build-essential binfmt-support qemu-user-static musl-tools curl wget iptables xz-utils btrfs-progs;
            apt-get clean;
            curl -o ./rustup-init https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init && \
            chmod +x /rustup-init;
            /rustup-init -y;
            rm -f /rustup-init;
            source $HOME/.cargo/env;
            cargo install cross;
      - run: $HOME/.cargo/bin/cross build --target armv7-unknown-linux-musleabihf --release; 
      - run:
          name: "Create Artifacts Package"
          command: |
            mkdir -p docker/bin/armv7-unknown-linux-musleabihf;
            cp -r ./docker/web docker/bin/armv7-unknown-linux-musleabihf/;
            cp target/armv7-unknown-linux-musleabihf/release/v-proxy docker/bin/armv7-unknown-linux-musleabihf/;
            tar -czvf docker/bin/armv7-unknown-linux-musleabihf.tar.gz docker/bin/armv7-unknown-linux-musleabihf/*;
      - persist_to_workspace:
          root: docker/bin
          paths:
            - armv7-unknown-linux-musleabihf.tar.gz
            - armv7-unknown-linux-musleabihf/
  
  aarch64-unknown-linux-musl:
    docker:
      - image: vproxy/ci-rust:202009130603
    steps:
      - checkout
      - run: sudo /usr/local/bin/dind; cross build --target aarch64-unknown-linux-musl --release; 
      - run:
          name: "Create Artifacts Package"
          command: |
            mkdir -p docker/bin/aarch64-unknown-linux-musl;
            cp -r ./docker/web docker/bin/aarch64-unknown-linux-musl/;
            cp target/aarch64-unknown-linux-musl/release/v-proxy docker/bin/aarch64-unknown-linux-musl/;
            tar -czvf docker/bin/aarch64-unknown-linux-musl.tar.gz docker/bin/aarch64-unknown-linux-musl/*;
      - persist_to_workspace:
          root: docker/bin
          paths:
            - aarch64-unknown-linux-musl.tar.gz
            - aarch64-unknown-linux-musl/

  deploy:
    docker:
      - image: vproxy/ci-rust:202009130603
    steps:
      - checkout
      - attach_workspace:
          at: docker/bin
      - run: dockerd
      - run: ls docker/bin; ls armv7-unknown-linux-musleabihf/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - x86_64-pc-windows-gnu
      - x86_64-unknown-linux-gnu
      - armv7-unknown-linux-musleabihf
      - deploy:
          requires:
            - x86_64-pc-windows-gnu
            - x86_64-unknown-linux-gnu
            - armv7-unknown-linux-musleabihf




