version: 2.1
jobs:
  build:
    docker:
      - image: vproxy/ci-rust:202009120931
    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - checkout
      - run: ls
      - run: pwd
      - run: printenv